name: Deploy online documentation

on:
  push:
    branches:
    - master

jobs:
  build-deploy:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Add PPA
      run: |
        sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
    - name: Install GRASS GIS and other dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq grass grass-dev grass-doc xlsx2csv
    - name: Process data
      run: |
        ./process.sh
    - name: Prepare artifacts to be published
      run: |
        mkdir artifacts
        mkdir artifacts/data
        cp buildings.geojson artifacts/data/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./artifacts
        force_orphan: true
