name: Deploy content

on:
  push:
    branches:
    - master

jobs:
  build-deploy:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add PPA
      run: |
        sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
    - name: Get dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gawk findutils
        xargs -a <(awk '! /^ *(#|$)/' ".github/workflows/apt.txt") -r -- \
            sudo apt-get install -y --no-install-recommends --no-install-suggests
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install keplergl in_place
    - name: Process data
      run: |
        ./process.sh
    - name: Generate web map
      run: |
        ./generate.sh
    - name: Prepare artifacts to be published
      run: |
        mkdir artifacts
        mkdir artifacts/data
        cp buildings.geojson artifacts/data/
        cp keplergl_AMO.html artifacts/
        cp keplergl_UPI.html artifacts/
        cp keplergl_TS.html artifacts/
        cp index.html artifacts/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./artifacts
        force_orphan: true
